# Utiliza a imagem oficial do MySQL 8.0 como base
FROM mysql:8.0

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Expor a porta 3306 para conexões externas
EXPOSE 3306

# Define a senha root do MySQL
ENV MYSQL_ROOT_PASSWORD=urubu100
# Comando para iniciar o MySQL ao iniciar o container
CMD ["mysqld"]
