]# Utiliza a imagem oficial do MySQL 8.0 como base
FROM ubuntu:22.04 AS builder
RUN apt-get update && apt-get install -y openjdk-21-jdk

WORKDIR /ubuntu/home/arquivos-docker



CMD ["java","-jar","./logviaconsole-1.0-SNAPSHOT-jar-with-dependencies.jar"]  


