# Utiliza a imagem oficial do MySQL 8.0 como base
FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=urubu100

ENV MYSQL_DATABASE=vorteil

# Define o diretório de trabalho dentro do container
COPY ./scripts/ScriptMySql.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"]
